FROM ubuntu:resolute

RUN apt-get update
RUN apt-get install -y ruby3.3 bundler
RUN apt-get install -y git wget xz-utils build-essential libyaml-dev

# Install Noto Fonts
RUN apt-get install -y fonts-noto

# Install Firefox
RUN wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null
RUN tee /etc/apt/sources.list.d/mozilla.sources > /dev/null << EOF
Types: deb
URIs: https://packages.mozilla.org/apt
Suites: mozilla
Components: main
Signed-By: /etc/apt/keyrings/packages.mozilla.org.asc
EOF
RUN tee /etc/apt/preferences.d/mozilla > /dev/null << EOF
Package: *
Pin: origin packages.mozilla.org
Pin-Priority: 1000
EOF
RUN apt-get update
RUN apt-get install -y firefox

# Install Geckodriver
RUN wget "https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz" -O geckodriver.tar.gz
RUN tar -xzf geckodriver.tar.gz -C /usr/local/bin

COPY . /app
WORKDIR /app
RUN bundle install
CMD ["bundle", "exec", "rspec"]
