name: Rspec
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Rspec Test
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Docker Build
        run: |
          docker build -f ./dockerfiles/Dockerfile.debian13-ruby32 . -t gkhtmltopdf-d13r32
          docker build -f ./dockerfiles/Dockerfile.ubuntu24-ruby32 . -t gkhtmltopdf-u24r32
          docker build -f ./dockerfiles/Dockerfile.ubuntu26-ruby33 . -t gkhtmltopdf-u26r33
      - name: Docker Run
        run: |
          docker run --rm gkhtmltopdf-d13r32
          docker run --rm gkhtmltopdf-u24r32
          docker run --rm gkhtmltopdf-u26r33
